# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7453540579bf65283f36b811448ae962a93fa42d8199d959f763babbb1ab3adc120645374dedebca545432799570bca7971065c9bd8c9797b06d8da3c15b7216

test:
  secret_key_base: ce1df73dc8af682863d0cc6fc58bbb50b7bc920e3f82d100eb3e177bd5b1bf40054f1f1c91790e4c4fa98219e403a9f68a7b2d502d8701836846e7b9a7c1e7bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
